version: '3.7'

services:
  pin_app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://pin_app_vet:3306/PinAppAws?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: admin1234
      DB_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    restart: always
    depends_on:
      pin_app_vet:
        condition: service_healthy
  pin_app_vet:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: admin1234
      MYSQL_DATABASE: PinAppAws
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10